@url_dev = http://localhost:3055/v1/api/

### signup/
POST {{url_dev}}/shop/signup/
Content-Type: application/json
x-api-key: b624a1fa359d6aca03f2f7ca19ad5a96153845347f09fdd18d843d9ea1f0ac7ed459cefc9e7ae1b60071e9fca5f089f037344419a854c7b161e52fd1f1bb468b

{
    "name": "Shop TIPS",
    "email": "quang5@gmail.com",
    "password": "abc123"
}